name: deploy-postgres

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          source: 'docker-compose.yml'
          target: './'
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy to Digital Ocean droplet via SSH actions
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          script: |
            sudo docker-compose down && sudo docker-compose up -d
